### ISSUE TITLE
Official PostgREST container

### ISSUE THREAD

**Issue by begriffs** [crealytics/postgrest-docker#1]
Hey @udl thanks for maintaining this repo to help people use postgrest more easily. Today I released an official repo on Dockerhub and I wonder if you could add a note redirecting people to that one? https://hub.docker.com/r/begriffs/postgrest/

The more people use a single repo the more we'll work out bugs and the better I can support it. Would also love your opinion about how to improve the official Dockerfile.

**Comment by udl** [comment]
Cool, yes I'll do that.
Btw, thank you for the super useful postgrest :)
